<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_email</name>
   <tag></tag>
   <elementGuidId>6c8992c1-b8cc-4c3e-8d3a-a5d84ed6e843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@class,'exampleInputEmail1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@id,'exampleInputEmail1')]</value>
      <webElementGuid>9ec01639-10a4-4b59-8031-e5e39a9db847</webElementGuid>
   </webElementProperties>
</WebElementEntity>
