<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_harga_tawar</name>
   <tag></tag>
   <elementGuidId>d2a41848-90df-4b97-8913-05336050e096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>2c287d70-6b84-4452-a54d-2391665b966c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
